### ISSUE TITLE
Expose more controls in sciml_train!

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqFlux.jl#132]
Right now the feature set is very bare. Some good things to add:

- [ ] Stopping criterion option on the current loss
- [ ] Stopping criterion option on the current value
- [ ] Stopping criterion due to total time

**Comment by ChrisRackauckas** [comment]
Handled by new callbacks.

**Comment by cems2** [comment]
pass in the Data from train instead of making it a global variable for Loss.

**Comment by ChrisRackauckas** [comment]
What would that change?

**Comment by cems2** [comment]
https://github.com/JuliaDiffEq/DiffEqFlux.jl/issues/162 <https://github.com/JuliaDiffEq/DiffEqFlux.jl/issues/162>

**Comment by cems2** [comment]
updated #162 just now with more details at the end
