### ISSUE TITLE
TrackerAdjoint on GPUs

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqFlux.jl#135]
```julia
using OrdinaryDiffEq, StochasticDiffEq, Flux, DiffEqSensitivity, DiffEqFlux, Zygote, Test, CuArrays
CuArrays.allowscalar(false)

mp = Float32[0.1,0.1] |> gpu
x = Float32[2.; 0.] |> gpu
xs = Float32.(hcat([0.; 0.], [1.; 0.], [2.; 0.])) |> gpu
tspan = (0.0f0,25.0f0)
dudt = Chain(Dense(2,50,tanh),Dense(50,2)) |> gpu

node = NeuralODE(dudt,tspan,Tsit5(),save_everystep=false,save_start=false,sensealg=TrackerAdjoint())
grads = Zygote.gradient(()->sum(node(x)),Flux.params(x,node))
```

@YingboMa can I get help tracking down (pun intended) what's going on here? Something is hitting scalar indexing but I don't know why.

**Comment by ChrisRackauckas** [comment]
It sounds like using Tracker makes this not work: https://github.com/JuliaDiffEq/RecursiveArrayTools.jl/blob/master/src/init.jl#L14-L21 but I don't get why that would be the case.

**Comment by ChrisRackauckas** [comment]
Trying to hack around and do the conversion to a matrix on the GPU drops gradients:

```julia
    vecs = Tracker.collect(Array(VectorOfArray(adapt.(Array,sol.u))))
    adapt(typeof(u0),vecs)
```

**Comment by ChrisRackauckas** [comment]
@MikeInnes do you have a solution for this? It's just changing a vector of TrackedArray{CuArray} into a concatenated TrackedArray{CuArray}. MWE:

```julia
using Tracker, CuArrays
u = [Tracker.TrackedArray(cu(rand(4))) for i in 1:2]
reduce(hcat,u)
```

**Comment by MikeInnes** [comment]
The MWE should be

```julia
using Tracker
reduce(hcat,[param(rand(4))])
```

There's nothing CuArrays specific about this except that we can't have `CuArray{TrackedReal}`, so it errors out. `hcat(u...)` works fine in both cases so the `reduce(hcat, ...)` form just needs an adjoint (possibly just forwarding to `hcat`).

**Comment by ChrisRackauckas** [comment]
Fixed in https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/pull/188
