### ISSUE TITLE
Box Constrained Optimization with sciml_train

### ISSUE THREAD

**Issue by pierrejacquet** [JuliaDiffEq/DiffEqFlux.jl#148]
Hi, I'm trying to optimize parameters of my system of ODE using DiffEqFlux by following the readme [Optimizing parameters of an ODE](https://github.com/JuliaDiffEq/DiffEqFlux.jl#optimizing-parameters-of-an-ode-for-an-optimal-control-problem). When I set everything and run the optimization the resulting parameters become negative and my solution unstable.

Is there any way to set boundaries on parameters (at least [0; +∞[ ) like [Box Constrained Optimization](https://github.com/JuliaNLSolvers/Optim.jl/blob/master/docs/src/user/minimization.md#box-constrained-optimization) with sciml_train ?

**Comment by ChrisRackauckas** [comment]
Added in https://github.com/JuliaDiffEq/DiffEqFlux.jl/pull/151

**Comment by pierrejacquet** [comment]
Thank you ! :)
