### ISSUE TITLE
FastDense is not found

### ISSUE THREAD

**Issue by jamesthesnake** [JuliaDiffEq/DiffEqFlux.jl#156]
Hello,
I installed all the packages and I keep getting the error that FastDense is not found/defined.  I am using the example code in the readme.

`
ERROR: LoadError: UndefVarError: FastDense not defined
Stacktrace:
 [1] top-level scope at none:0
'`

Any idea what would cause this packaging wise?

**Comment by ali-ramadhan** [comment]
Hmmm, which version of DiffEqFlux are you on? `FastDense` was a recent addition.

If you go into package mode (by typing `]` at the Julia REPL) and post the output of
```
julia> ]
(v1.3) pkg> status
```
that would be helpful.

**Comment by jamesthesnake** [comment]
[c52e3926] Atom v0.11.2
  [aae7a2af] DiffEqFlux v0.4.0
  [41bf760c] DiffEqSensitivity v3.2.0
  [587475ba] Flux v0.8.3
  [7073ff75] IJulia v1.20.0
  [e5e0dc1b] Juno v0.7.2
  [429524aa] Optim v0.20.1
  [1dea7af3] OrdinaryDiffEq v5.14.0
  [91a5bcdd] Plots v0.28.4

**Comment by ChrisRackauckas** [comment]
Are you using Julia v1.3?

**Comment by ali-ramadhan** [comment]
> `[aae7a2af] DiffEqFlux v0.4.0`

Ah there's your problem! v0.4.0 is very old, the current version is v1.3.1.

What version of Julia are you running? It's possible that v0.4.0 is the latest compatible with your version.

I would upgrade to Julia 1.3 and `] add DiffEqFlux` again, and you should get the latest version.

**Comment by jamesthesnake** [comment]
ok I am running like 1.06 or whatever the most stable version is , I'l update to 1.3

**Comment by ChrisRackauckas** [comment]
Yup that explains it. There's too many dependencies that require 1.3, so this library has to require 1.3. That said, I do think that the next stable version should come out "soon" (summer?) as Julia v1.5, so that will fix a lot of these issues (since a lot of these now core features, like multithreading, are used throughout the dependencies!).
