### ISSUE TITLE
What types of DEs will eventually be supported ?

### ISSUE THREAD

**Issue by aussetg** [JuliaDiffEq/DiffEqFlux.jl#16]
Hi,

In theory what problems can we get gradients from ? All with Zygote ? Just some ? (BVP is one of them hopefully :) )

Thanks for your awesome work

Guillaume

**Comment by ChrisRackauckas** [comment]
In theory all of them. Did you try a `BVPProblem` yet? The shooting methods should work given the ODE solvers work. I haven't checked if the other ones work as well.

**Comment by aussetg** [comment]
I'll try, it's my first time using Flux and DiffEq so I'm familiarizing myself and I'll try to coerce the type system to do my bidding

**Comment by ChrisRackauckas** [comment]
This seems closed. If you have an issue with any DEProblem, post an example of it and we can get it working. In theory, any works.
