### ISSUE TITLE
BoundsError in README example

### ISSUE THREAD

**Issue by gileshd** [JuliaDiffEq/DiffEqFlux.jl#24]
I have tried to run the example in the README however `diffeq_rd()` throws a BoundsError [error message attached](https://github.com/JuliaDiffEq/DiffEqFlux.jl/files/2861990/diffeq_rd_error_message.txt).

This is happening with:
julia: v1.1.0
DiffEqFlux: v.0.2.0
DifferentialEquations: v6.3.0
Flux: v0.7.3

The same error occurs when implementing the examples in the Flux [model-zoo](https://github.com/FluxML/model-zoo/tree/master/other/diffeq) with the above versions.

Following the instructions on the model-zoo page, using the following package versions:

julia: v1.0.3
DiffEqFlux: v.0.2.0
DifferentialEquations: v5.3.1
Flux: v0.7.2

Both the DiffEqFlux readme example and the Flux model-zoo examples work.
As far as I can tell it is a problem with the julia version however I am very new to the language and so am not sure.

**Comment by ChrisRackauckas** [comment]
I think one of our updates did something to the dimension handling. We'll get this fixed.

**Comment by ChrisRackauckas** [comment]
The bounds error is now fixed. Tests are passing again. Let me know if anything else comes up.

**Comment by dykuang** [comment]
Hello, I am a newbie in Julia and was trying to run a modified example myself (attached below) according to part of the sample code in the model zoo. Everything went fine except for the very last line where it threw a BoundError. Packages are up-to-date, I did not know where the mistakes are, any help would be appreciated. 

```
using Flux, DiffEqFlux, DifferentialEquations, Plots

function func(du, u, p, t) 
  a, b, c, d = p
  du[1] =  exp(a-b/8.3145/t)*(u[1])^c*(1.0-u[1])^d
end

u0 = [0.05]
tspan = (300.0, 1200.0)
p = [20.0, 150000.0, 1.0, 1.0]
prob = ODEProblem(func, u0, tspan, p)

sol = solve(prob,Rodas4(), saveat = 5, maxiters=1e7)
scatter(sol[1,:])

dudt = Chain(Dense(2,50,relu),
             Dense(50,2,relu),
             x -> [exp(20.0-150000.0/8.3146./x[2]).*x[1]; 1.0]) 
ps = Flux.params(dudt)

u0 = [0.05;300.0]
n_ode = x -> neural_ode(dudt, x, tspan, Tsit5(), saveat = 5)

sol_data = Array(sol)
function predict_n_ode() 
  n_ode(u0)
end

loss_n_ode() = sum(abs2, predict_n_ode()[1,:] - sol_data[1,:])

data = Iterators.repeated((), 50)
opt = ADAM(0.01)

cb = function()
  display(loss_n_ode())
end

cb()
Flux.train!(loss_n_ode, ps, data, opt, cb=cb)
```

**Comment by ChrisRackauckas** [comment]
That's hitting https://github.com/JuliaDiffEq/DiffEqFlux.jl/issues/12 and then a type issue with argtail, which I'll file as a separate issue. Hmm...
