### ISSUE TITLE
Mixing neural and normal ODEs

### ISSUE THREAD

**Issue by mkalia94** [JuliaDiffEq/DiffEqFlux.jl#41]
Hi! Firstly, thanks for a wonderful package, I expect to see a lot of applications come out of this!

My problem refers to [#15](https://github.com/JuliaDiffEq/DiffEqFlux.jl/issues/15). The solution that was posted at the end works. However, if I try to extend the idea to a higher-dimensional ODE, this doesn't work. Here's an example:
```julia
using DiffEqFlux, Flux,  DifferentialEquations

# Generate ODE---------------------------------------------------
par = Float32[10.0, 28.0,8/3]
tspan = (0.0,10.0)
Kgain = Chain(Dense(2,10,tanh),
              Dense(10,10,tanh),
              Dense(10,2))

function dudt_(u::TrackedArray,p,tt)
  nn = Kgain(u[1:2])
  Flux.Tracker.collect([nn;[u[1]*u[2] - p[3]*u[3]]])
end
function dudt_(u::AbstractArray,p,tt)
  nn = Flux.data(Kgain(u[1:2]))
  collect([nn;[u[1]*u[2] - p[3]*u[3]]])
end

pr = param(par)
x0 = Float32[0.1;0.1;0.1]
prob = ODEProblem(dudt_,x0,tspan,pr)
diffeq_rd(pr,prob,Tsit5())
```

This gives the following error:
`MethodError: vcat(::TrackedArray{…,Array{Float32,1}}, ::Array{Tracker.TrackedReal{Float32},1}) is ambiguous. Candidates:
  vcat(V::AbstractArray{T,1} where T...) in Base at abstractarray.jl:1233
  vcat(A::Union{AbstractArray{T,1}, AbstractArray{T,2}} where T...) in Base at abstractarray.jl:1296
  vcat(A::Union{UniformScaling, Union{AbstractArray{T,1}, AbstractArray{T,2}} where T}...) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/uniformscaling.jl:258
  vcat(A::AbstractArray, B::AbstractArray) in Base at abstractarray.jl:1517
  vcat(x::Union{TrackedArray, TrackedReal}, xs::Union{Number, AbstractArray}...) in Tracker at /home/manu/.julia/packages/Tracker/6wcYJ/src/lib/array.jl:167
Possible fix, define
  vcat(::TrackedArray{T,1,A} where A<:AbstractArray{T,1} where T, ::AbstractArray{T,1} where T)`

Any help is appreciated! Thanks in advance :)

**Comment by ChrisRackauckas** [comment]
You just had some type issues. Here's a working code:

```julia
using DiffEqFlux, Flux,  OrdinaryDiffEq

# Generate ODE---------------------------------------------------
par = Float32[10.0, 28.0,8/3]
tspan = Float32.((0.0,10.0))
Kgain = Chain(Dense(2,10,tanh),
              Dense(10,10,tanh),
              Dense(10,2))

function dudt_(u::TrackedArray,p,tt)
  nn = Kgain(u[1:2])
  Flux.Tracker.collect([nn;u[1]*u[2] - p[3]*u[3]])
end
function dudt_(u::AbstractArray,p,tt)
  nn = Flux.data(Kgain(u[1:2]))
  collect([nn;u[1]*u[2] - p[3]*u[3]])
end

pr = param(par)
x0 = Float32[0.1;0.1;0.1]
prob = ODEProblem(dudt_,x0,tspan,pr)
diffeq_rd(pr,prob,Tsit5())
```
