### ISSUE TITLE
Allocations using diffeq_rd()

### ISSUE THREAD

**Issue by JMmontilla** [JuliaDiffEq/DiffEqFlux.jl#51]
I hace noticed that a considerable amount of allocation appear when using the function `diffeq_rd` for evaluating the ODE with the tracked parameters. In this example it is shown very clearly:
```julia
using Flux, DiffEqFlux, DifferentialEquations, BenchmarkTools

const μ     = 2.0451149878572323e6
const wt    = 0.0003766355744484957

function coordSpher(X::Vector)
    x, y, z, vx, vy, vz = X
    r   = sqrt(x^2+y^2+z^2)
    ϕ   = asin(z/r)
    λ   = atan(y,x)
    return r,ϕ,λ
end
function ast(f,x,p,t,μ=μ,wt=wt) # x : estado en coordenadas cartesianas
    r, ϕ, λ = coordSpher(x)
    J2,J22  = p
    Rm      = 1.0
    Ur      = -μ/r^4*( r^2 + J2*3/2*Rm^2*(1-3*sin(ϕ)^2)-9*J22*Rm^2*cos(ϕ)^2*cos(2λ) )
    Up      = -μ/r^3*6*Rm^2*cos(ϕ)*sin(ϕ)*(J2/2-J22*cos(2λ))
    Ul      = μ/r^3*6*J22*Rm^2*cos(ϕ)^2*sin(2*λ)
    Gx      = Ur*cos(ϕ)*cos(λ) + Ul/r*(-sin(ϕ)*cos(λ)) +Up/r/cos(ϕ)*-sin(λ)
    Gy      = Ur*cos(ϕ)*sin(λ) + Ul/r*(-sin(ϕ)*sin(λ)) +Up/r/cos(ϕ)*-cos(λ)
    Gz      = Ur*sin(ϕ) + Ul/r*cos(ϕ)
    f[1] = x[4]
    f[2] = x[5]
    f[3] = x[6]
    f[4] = Gx + 2*x[5]*wt    + x[1]*wt^2
    f[5] = Gy - 2*x[4]*wt   + x[2]*wt^2
    f[6] = Gz
end

u0 = [-18105.392, -88924.165, 51340.390, -28.859, 6.012, 0.465]
tspan = (0.0,2e4)
p = [2.218190645002624e8, -1.4619343719968584e8] # true parameters

prob = ODEProblem(ast,u0,tspan,p)

data_sol = solve(prob,Tsit5(),saveat=1000.0,abstol=1e-7,reltol=1e-6)

pfd = param(p)  # using the same paramters just to check the allocations in same conditions
function predict_rd() # Our 1-layer neural network
  diffeq_rd(pfd,prob,Tsit5(),saveat=1000.0,abstol=1e-7,reltol=1e-6)
end
loss_rd() = sum(abs2,predict_rd()-data_sol) # loss function

@benchmark solve(prob,Tsit5(),saveat=1000.0,abstol=1e-7,reltol=1e-6)
@benchmark predict_rd()
```

Using the `solve` of `DifferentialEquations` yields:
```julia
BenchmarkTools.Trial: 
  memory estimate:  10.50 KiB
  allocs estimate:  119
  --------------
  minimum time:     79.711 μs (0.00% GC)
  median time:      85.053 μs (0.00% GC)
  mean time:        91.088 μs (1.39% GC)
  maximum time:     3.673 ms (96.39% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

While the `diffeq_rd` on the other hand uses almost 10 MiB of memory and is much slower:

```julia
BenchmarkTools.Trial: 
  memory estimate:  9.18 MiB
  allocs estimate:  291317
  --------------
  minimum time:     1.914 ms (0.00% GC)
  median time:      2.385 ms (0.00% GC)
  mean time:        5.988 ms (61.87% GC)
  maximum time:     22.093 ms (84.58% GC)
  --------------
  samples:          834
  evals/sample:     1
```

I thought it was a problem of the function `predict_rd()` using `prob` from the global scope, but even feeding it to the function as input gives the same result, so I don't know whats happening. For what I understand of the source code of `diffeq_rd` it basically remakes the ODE with the tracked parameters and applies `solve`, so maybe the inefficiency comes from those tracked parameters? 

Is there a solution for this or is it a limitation of how Flux works?

**Comment by ChrisRackauckas** [comment]
>Is there a solution for this or is it a limitation of how Flux works?

It's a limitation of tracing-based JITs like Tracker.jl (Flux's current AD). Essentially, it needs to build a computational graph on the fly of each operation it runs (its trace), and then runs that backwards. That backwards run of course is a dynamically generated operation graph that is reversed, so its not inferred since the types of the functions aren't known until the current value is known (since for example, the trace can change depending on the branch that is taken). Thus, you won't see this fixed with any tracing-based JIT, it's just a fundamental limitation of this method. For machine learning, this is fine because the cost per operation is high enough since you're doing convolutions and matrix multiplications. The authors of JAX specifically say this is okay for all programs someone might want to AD...

But it's not okay for this discipline, which is why reverse mode doesn't work well here. https://arxiv.org/abs/1812.01892 describes this in more detail. Zygote.jl works without traces by doing a source-to-source transform, building a new Julia program for the reverse mode function, which can be JIT compiled and all of that. Thus Zygote will fix this issue.

**Comment by JMmontilla** [comment]
Well that clarifies everything :blush: . Thanks for the in-depth answer, I'll check Zigote.jl right away :smile:

**Comment by JMmontilla** [comment]
> Thus Zygote will fix this issue.
@ChrisRackauckas does Zygote.jl support differentiation with ODEs at the moment? I haven't been able to make it work and I have found this issue: https://github.com/FluxML/Zygote.jl/issues/37 , but it is old and I'm not sure if still applies.

**Comment by ChrisRackauckas** [comment]
Will. It doesn't right now 🌮

**Comment by JMmontilla** [comment]
@ChrisRackauckas got it, thanks.

**Comment by JMmontilla** [comment]
@ChrisRackauckas Is there a way to get notified when Zygote.jl is compatible with ODEs? Or alternatively, will you add that to the documentation of DifferentialEquations.jl when that happens? I just want to know it when both are compatible, my goal is to use this technique to compute the internal mass distribution of asteroids using navigational data, and I thought that using DiffEqFlux.jl would be an interesting method, but since the AD method used right now is so inefficient I will wait, as the asteroid will eventually be modeled by several hundred parameters (if not more) and the present AD method is just too slow.

In any case, I just wanted to know a way to be notified when ODEs are a thing in the Zygote world. 

Thanks.

**Comment by ChrisRackauckas** [comment]
Is using adjoint not possible on your problem?

**Comment by ChrisRackauckas** [comment]
Maybe it works now a little bit: https://github.com/FluxML/Zygote.jl/issues/243

**Comment by ChrisRackauckas** [comment]
Still adjoint would be preferred

**Comment by JMmontilla** [comment]
@ChrisRackauckas thanks, will try :blush:
