### ISSUE TITLE
"MethodError: no method matching gemm!" error when using Rosenbrock23 with diffeq_rd.

### ISSUE THREAD

**Issue by tgrassi** [JuliaDiffEq/DiffEqFlux.jl#55]
Hi, thanks for the great package!

I found a problem when combining `diffeq_rd` and the `Rosenbrock23` solver.
If I run the Lotka-Volterra basic example provided named "Train an ODE to satisfy an objective"
(https://github.com/FluxML/model-zoo/blob/da4156b4a9fb0d5907dcb6e21d0e78c72b6122e0/other/diffeq/ode.jl) everything works as expected.

I replace `Tsit5()` with `Rosenbrock23(autodiff=false)` in the function `predict_rd` on line 30 and it still works.

Now, I increase the number of variables from 2 to 30 in the differential equations function by changing the lines marked with `<<<<<<<` here below (note that the additional variables do not affect the solution)
```julia
using Flux, DiffEqFlux, DifferentialEquations, Plots

## Setup ODE to optimize
function lotka_volterra(du,u,p,t)
  x, y = u
  α, β, δ, γ = p
  du[1] = dx = α*x - β*x*y
  du[2] = dy = -δ*y + γ*x*y
  du[3:end] .= 0e0 # <<<<< ADD
end
# u0 = [1.0,1.0] # <<<<< REMOVE
u0 = ones(30) # <<<<< ADD
tspan = (0.0,10.0)
p = [1.5,1.0,3.0,1.0]
prob = ODEProblem(lotka_volterra,u0,tspan,p)

# Verify ODE solution
sol = solve(prob,Tsit5())
plot(sol)

# Generate data from the ODE
sol = solve(prob,Tsit5(),saveat=0.1)
A = sol[1,:] # length 101 vector
t = 0:0.1:10.0
scatter!(t,A)

# Build a neural network that sets the cost as the difference from the
# generated data and 1

p = param([2.2, 1.0, 2.0, 0.4]) # Initial Parameter Vector
function predict_rd() # Our 1-layer neural network
  diffeq_rd(p,prob,Rosenbrock23(autodiff=false),saveat=0.1)[1,:] # <<<<<<< CHANGED
end
loss_rd() = sum(abs2,x-1 for x in predict_rd()) # loss function

# Optimize the parameters so the ODE's solution stays near 1

data = Iterators.repeated((), 100)
opt = ADAM(0.1)
cb = function () #callback function to observe training
  display(loss_rd())
  # using `remake` to re-create our `prob` with current parameters `p`
  display(plot(solve(remake(prob,p=Flux.data(p)),Tsit5(),saveat=0.1),ylim=(0,6)))
end
# Display the ODE with the initial parameter values.
cb()
Flux.train!(loss_rd, [p], data, opt, cb = cb)
```
These changes produce the following error
```
ERROR: LoadError: MethodError: no method matching gemm!(::Char, ::Char, ::Tracker.TrackedReal{Float64}, ::SubArray{Tracker.TrackedReal{Float64},2,Array{Tracker.TrackedReal{Float64},2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}, ::SubArray{Tracker.TrackedReal{Float64},2,Array{Tracker.TrackedReal{Float64},2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}, ::Tracker.TrackedReal{Float64}, ::SubArray{Tracker.TrackedReal{Float64},2,Array{Tracker.TrackedReal{Float64},2},Tuple{UnitRange{Int64},UnitRange{Int64}},false})
Closest candidates are:
  gemm!(::AbstractChar, ::AbstractChar, ::Float64, ::Union{AbstractArray{Float64,1}, AbstractArray{Float64,2}}, ::Union{AbstractArray{Float64,1}, AbstractArray{Float64,2}}, ::Float64, ::Union{AbstractArray{Float64,1}, AbstractArray{Float64,2}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/blas.jl:1111
  gemm!(::AbstractChar, ::AbstractChar, ::Float32, ::Union{AbstractArray{Float32,1}, AbstractArray{Float32,2}}, ::Union{AbstractArray{Float32,1}, AbstractArray{Float32,2}}, ::Float32, ::Union{AbstractArray{Float32,1}, AbstractArray{Float32,2}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/blas.jl:1111
  gemm!(::AbstractChar, ::AbstractChar, ::Complex{Float64}, ::Union{AbstractArray{Complex{Float64},1}, AbstractArray{Complex{Float64},2}}, ::Union{AbstractArray{Complex{Float64},1}, AbstractArray{Complex{Float64},2}}, ::Complex{Float64}, ::Union{AbstractArray{Complex{Float64},1}, AbstractArray{Complex{Float64},2}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/blas.jl:1111
  ...
```

Now, if I go back from `Rosenbrock23(autodiff=false)` to `Tsit5()` the code can handle all the 30 variables and produces the same results as the 2-variables case (as expected).

To recap:
- 2 variables + Tsit5: OK
- 2 variables + Rosenbrock23: OK
- 30 variables + Rosenbrock23: FAIL (gemm! error)
- 30 variables + Tsit5: OK

Other info:
- Same problem with `TRBDF2()` and in general with solvers for stiff ODEs.
- It seems to work fine up to 16 variables (i.e. with 17 I get the gemm! error).
- Found the same behaviour in more complex set-ups.

What am I doing wrong? Thanks in advance.

---------------------
My system:
`Linux 4.15.0-54-generic #58~16.04.1-Ubuntu`

Julia Version 1.1.1 (2019-05-16), other packages are
```
  "Sundials"              => v"3.6.1"
  "Atom"                  => v"0.8.8"
  "Optim"                 => v"0.19.0"
  "Juno"                  => v"0.7.0"
  "TensorFlow"            => v"0.11.0"
  "StatsBase"             => v"0.31.0"
  "DiffEqFlux"            => v"0.5.0"
  "Flux"                  => v"0.8.3"
  "Plots"                 => v"0.25.3"
  "DifferentialEquations" => v"6.6.0"
  "ImageView"             => v"0.9.0"
```

**Comment by ChrisRackauckas** [comment]
When the size increases, we do an auto-blocking to speed up OpenBLAS. However, that has a `BLAS.gemm` call in there.

https://github.com/YingboMa/RecursiveFactorization.jl/blob/master/src/lu.jl#L98

@YingboMa can we just put an `if StridedArray gemm! otherwise ...` on that?

**Comment by tgrassi** [comment]
Hi Chris, thanks for the answer.
It would be great to have this available for larger stiff systems.
Also an option to not use OpenBLAS might help.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/YingboMa/RecursiveFactorization.jl/releases/tag/v0.0.1 .

Though looking at your example, the way you're computing it is going to be really slow. You should probably use adjoint, and we should change the README example.

**Comment by tgrassi** [comment]
Thnaks @YingboMa and @ChrisRackauckas for the fix and for the suggestion, I will try adjoint.
