### ISSUE TITLE
save_start=false argument ignored for neural_ode solve

### ISSUE THREAD

**Issue by jessebett** [JuliaDiffEq/DiffEqFlux.jl#64]
Tested here: https://github.com/jessebett/DiffEqFlux.jl/blob/master/test/solver_options.jl

If you call `neural_ode` with `save_start=false` it still returns the start. I believe this needed to be overridden internally to get adjoint to work, but what is returned should respect this argument.

It is very common to run these solves only requiring the output to be saved. It would be nice if there was an option like `save_only` in this case would be the end of the timespan.

**Comment by ChrisRackauckas** [comment]
It's supposed to be handled right here: https://github.com/JuliaDiffEq/DiffEqFlux.jl/blob/master/src/Flux/layers.jl#L73-L88

**Comment by jessebett** [comment]
aha, I'm not touching that with options `save_everystep = false, save_start=false`
