### ISSUE TITLE
neural_ode solve leaves gpu

### ISSUE THREAD

**Issue by jessebett** [JuliaDiffEq/DiffEqFlux.jl#65]
This test here fails on master:
https://github.com/jessebett/DiffEqFlux.jl/blob/057baa62f9eb5a2d40f147252aa83dc5bdc1bf99/test/neural_de_gpu.jl#L152-L168

Calling `neural_ode` with initial condition and dudt on gpu does not return a CuArray.

**Comment by ChrisRackauckas** [comment]
🐱
