### ISSUE TITLE
ERROR: LoadError: MethodError: objects of type Tracker.Params are not callable - partial_neural.jl

### ISSUE THREAD

**Issue by frank-ccc** [JuliaDiffEq/DiffEqFlux.jl#77]
Hello,
when running partial_neural.jl I found the following issue:

66.70833f0 (tracked)
ERROR: LoadError: MethodError: objects of type Tracker.Params are not callable
Stacktrace:
 [1] top-level scope at C:\Users\frank\Documents\GitHub\DiffEqFlux.jl\test\partial_neural.jl:38
in expression starting at C:\Users\frank\Documents\GitHub\DiffEqFlux.jl\test\partial_neural.jl:38

I am not sure why it happens.
Thank you

**Comment by ChrisRackauckas** [comment]
What versions do you have? `]st`. The tests were pretty recently run, so the release version should be fine.

**Comment by frank-ccc** [comment]
I seem to have understood what the issue is. I ran the script from atom and had run other examples before this one. If I restart the repl, the issue no longer happens. 
However, when I run the script twice, I get a new typeof error.

**Comment by ChrisRackauckas** [comment]
That's interesting. What's the error there? But yeah, if you run different scripts in the same REPL, they might all be using the same function name so they might clash.

**Comment by frank-ccc** [comment]
The error seems to be nothing important:
ERROR: LoadError: BoundsError: attempt to access 2-element Array{Float32,1} at index [1:41]
Thank you though, Chris. Your DiffEqFlux.jl package is really great!

**Comment by ChrisRackauckas** [comment]
That probably is because the script is modifying something and assumes it's run sequentially or once. It should cause any real issues.
